service: schedule-notification-service

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  stage: dev

functions:
  sendScheduleNotification:
    handler: helpers/lambdaHandler.sendEmailNotifications
    events:
      - http:
          path: send-schedule-notification
          method: post
      - schedule:
          rate: rate(1 minute) # This will trigger every minute
          enabled: true
    environment:
      SENDER_EMAIL: "your-email@example.com" # Replace with your verified SES email

plugins:
  - serverless-offline

custom:
  serverless-offline:
    port: 3000
